# Generated by Django 2.2.7 on 2019-12-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20191217_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsession',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('declined', 'declined'), ('finished', 'finished')], default='pending', max_length=10),
        ),
    ]
