# Generated by Django 2.2.7 on 2019-12-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20191217_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsession',
            name='status',
            field=models.CharField(choices=[('PENDING_STATUS', 'pending'), ('APPROVED_STATUS', 'approved'), ('DECLINED_STATUS', 'declined'), ('FINISHED_STATUS', 'finished')], default='pending', max_length=10),
        ),
    ]
