# Generated by Django 2.2.7 on 2019-12-30 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='discussionreport',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='discussion',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='discussionreport',
            name='text',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='DiscussionComments',
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussioncomments', to='discussions.Discussion'),
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussioncomments', to=settings.AUTH_USER_MODEL),
        ),
    ]
