# Generated by Django 2.2.7 on 2019-12-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_city_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='user',
        ),
    ]
