# Generated by Django 2.2.7 on 2019-12-23 20:41

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='/media/photos/no_photo/placeholder.png', null=True, upload_to=users.models.get_user_photo_path),
        ),
    ]
