# Generated by Django 2.2.7 on 2019-11-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_birth',
            new_name='birthday',
        ),
    ]
