# Generated by Django 2.2.7 on 2019-12-24 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_city_user'),
        ('users', '0002_auto_20191223_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='locations.City'),
        ),
    ]
