# Generated by Django 2.2.7 on 2019-12-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_delete_nativelanguage'),
        ('users', '0003_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='native_languages',
            field=models.ManyToManyField(to='languages.Language'),
        ),
    ]
