# Generated by Django 2.2.7 on 2019-12-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20191122_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninglanguage',
            name='skills',
            field=models.CharField(blank=True, choices=[('a1', 'Beginner'), ('a2', 'Elementary'), ('b1', 'Intermediate'), ('b2', 'Upper Intermediate'), ('c1', 'Advanced'), ('c2', 'Proficient')], max_length=20),
        ),
    ]
