# Generated by Django 2.2.7 on 2019-12-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20191216_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NativeLanguage',
        ),
    ]
